using Bolt.Helpers;
using Bolt.Server;
using Owin;

namespace Server
{
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            JsonSerializer serializer = new JsonSerializer();
            ServerConfiguration configuration = new ServerConfiguration(serializer, new JsonExceptionSerializer(serializer));

            // register bolt 
            app.UseBolt(configuration);

            // register our custom contract - extension generated by bolt tool 
            app.UseContactListProvider<ContactListProvider>();
        }
    }
}