using Bolt.Client;
using Bolt.Client.Channels;
using Contract;
using System;

namespace Client.Bolt
{
    /// <summary>
    /// The session initiation and destroy logic is not generated by bolt so we need to manually define it 
    /// and use this class when creating proxy with session support.
    /// </summary>
    internal class MemoServiceChannel : RecoverableStatefullChannel<MemoServiceProxy>
    {
        private readonly string _user;

        public MemoServiceChannel(string user, Uri server, ClientConfiguration clientConfiguration)
            : base(server, clientConfiguration)
        {
            _user = user;
        }

        public MemoServiceChannel(RecoverableStatefullChannel<MemoServiceProxy> proxy)
            : base(proxy)
        {
        }

        protected override void OnProxyOpening(MemoServiceProxy contract)
        {
            contract.Login(_user);
        }

        protected override void OnProxyClosing(MemoServiceProxy contract)
        {
            contract.Logoff();
        }
    }
}
